version: "3.8"
services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000" 
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

networks:
  app_network:
    driver: bridge
